.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH uu_who 1  "uu_who 0.0.27" 
.SH NAME
uu_who \- Print the current username.
.SH SYNOPSIS
\fBuu_who\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Print the current username.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.0.27
