[package]
name = "uu_base64"
version = "0.0.27"
authors = ["uutils developers"]
license = "MIT"
description = "base64 ~ (uutils) decode/encode input (base64-encoding)"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/main/src/uu/base64"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2021"

readme.workspace = true


[dependencies]
uucore = { workspace = true, features = ["encoding"] }
clap = { workspace = true }

[[bin]]
name = "base64"
path = "src/main.rs"
