[package]
name = "uu_arch"
version = "0.0.27"
authors = ["uutils developers"]
license = "MIT"
description = "arch ~ (uutils) display machine architecture"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/main/src/uu/arch"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2021"

readme.workspace = true

[dependencies]
platform-info = { workspace = true }
clap = { workspace = true }
uucore = { workspace = true }

[build-dependencies]
clap = "4.4"
clap_complete = "4.4"
clap_mangen = "0.2"
uucore = { workspace = true }

[[bin]]
name = "arch"
path = "src/main.rs"
